name: employee_qr
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  firebase_core: ^1.12.0
  firebase_database: ^9.0.6
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.3
  get_storage: ^2.0.3

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

  lint: ^1.8.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/splash.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Dosis
      fonts:
        - asset: assets/font/Dosis.ttf
